language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
script:
- npm run build
- npm test
after_success:
  'cd ./build && find . -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp://pedak.me/proc/react-forum/{} \;'
env:
  global:
  - secure: cHMQ6z1amZERSK9u2VbJR6MrvlrUeT/pbF0DJZM+MNAP6SaTZUFvG7bcNIrcCYn+RfOIBU019aUNKUqCZJlAQdhiNw8fAGFXaIiJ6kaHuvVpm7JWG+9tpIC8s3MWWjppUWhnD4pQ0COKvKDSA+lvyFl0iMH39JtqGGpHmoUxflIry8kz5tn9XS2iwxce4MdbSiHOMj+/F+b2aaqfHOjPZQnTz/Gc+fdSbKrpDJyuKTeZmqYIH0qfqmAULKwSIVHkrKbtGYbwlwtvtneP60o5nzOJjTKbn5vyWHRuvK54/OYPXTj3Qs/beb+I1U5y+zhBvfQA/+gcchowOYTJ1qb7nYdY8Ga/krMeLvsVJS9/GGhsh2o9+jzHkhyCGjkQaxUgEcLE1HV2LUn7VxrLkolcsdE5COClUDAZy65xYwY5HgLnGw2Ddy0Nwjkc1viQSfu2Hd8+j2dhhK71XKbxLme+Yljzapi37gUifMGSXc/Zw/grFpGs7mu1rNT2rUxKIo3p9HFNFGzKPWIls4d48jwcxeLciReTpsuRKAUs3LXnPmbsmOq6yAmDPUe1SWZULKEBz4YbCYLpqOPcL1xLQyZUHY1ZC7lH1XkuAk/1oCQ7qVkglnHoHzkKASVBSp2Kvt+CC/+DlUN8UYs07vqi9pYiLkw4k70voESsGQX/zyv+/TI=
  - secure: FxgHUhnGDDD+Whd14VBoVz51OOXsKC667hqJCbXXSUlvBApOKHFleFvKG5xr40ZO5SW0eDd26oOCNJcn4ETLZpDRhaYASChBQn3j8RfgJjvX4taqr88HJ/jCv7ck5csMZ3J1tmUZ0Xe+hWHQLWKlotRY696bSPkjsCtQHMznsIpqe7XqlD55IZF3ATh/WPeLS/3rXg/sIxJtALbERhfXaHJ/cepr44rVfb3QWnZgu7AjlcYUx1yzElPRwTWVKvz/2B9/9KLAFzA8CdRkcEO8CAUAylGWXpbk4kuWzleXBRGm9rCdmfU1oqaX38Se9p6A/TlYfSJqKkJyLCGCbKC6Qta9zyXQCOJjRvRY03FJ6er2WTY6eYtfWryvj7goQxvX96WZu7nupyB2Ooyf6Ce0z5nhTmvB8hq410HqyFKMYZePk8SW5OUr8nT9ov1EDGs54NtlUVEe3i2vskYQJafGeKPVfSJvguCrerdlZug2OGm4ywxxnqNJP/uQKyCtR/janjZI1nSOCJrY79xlvTEzwRhCiJxP2skTQ/a6negmH7QoWtwruO613n4NijDl3BnN3gwND7Rp9f12qCHXvJR+UrGzv8+k5r7nC1CTsI/Tr4ppkGYJaFv1F2phk2XgEqwHOn2AXO8spEpjElDbM4rJcPkKKfno4vV+uL2U2wHyFh0=
